spring:
  application:
    name: core-backend
  profiles:
    # active: mysql
    default: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

server:
  port: 8081
