spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/projekan
    username: rascal
    password: ""
    driver-class-name: org.postgresql.Driver
  # jpa:
  #   properties:
  #     hibernate:
  #       dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      schema-locations: classpath:ddl/postgres/schema-extra.sql
