###### MODIFIERS ######
### Create
POST {{baseUrl}}/menus/modifiers
Content-Type: application/json

{
    "name": "Size",
    "minSelection": 1,
    "maxSelection": 1,
    "options": [
        { "name": "small", "additionalPrice": 0 },
        { "name": "medium", "additionalPrice": 500 },
        { "name": "big", "additionalPrice": 1000 }
    ]
}

### Get
GET {{baseUrl}}/menus/modifiers/1

### Search active or GetAll
GET {{baseUrl}}/menus/modifiers

### Update
PUT {{baseUrl}}/menus/modifiers/2
Content-Type: application/json

{
    "name": "size",
    "minSelection": 1,
    "maxSelection": 1,
    "options": [
        { "name": "small", "additionalPrice": 0 },
        { "name": "medium", "additionalPrice": 500 },
        { "name": "large", "additionalPrice": 1000 }
    ]
}

### Delete
DELETE {{baseUrl}}/menus/modifiers/2


###### MENU CATEGORIES ######
### Create
POST {{baseUrl}}/menus/categories
Content-Type: application/json

{
    "displayName": "coffee",
    "categoryCode": "coffee",
    "displayOrder": 1
}

### Get
GET {{baseUrl}}/menus/categories/1

### Search active or GetAll
GET {{baseUrl}}/menus/categories?displayName=cof&showDeleted=false

### Update
PUT {{baseUrl}}/menus/categories/1
Content-Type: application/json

{
    "displayName": "Hot Beverages",
    "categoryCode": "COffee",
    "displayOrder": 1
}

### Delete
DELETE {{baseUrl}}/menus/categories/2

### Restore
PATCH {{baseUrl}}/menus/categories/1/restore


###### MENUS ######
### Create
POST {{baseUrl}}/menus
Content-Type: application/json

{
    "name": "Americano",
    "categoryIds": [1],
    "description": "Strong coffee shot",
    "imageUrls": ["/assets/images/menus/coffee/americano.jpg"],
    "basePrice": 7000,
    "isAvailable": true,
    "ModifierTypeIds": [1]
}

### Get
GET {{baseUrl}}/menus/1

### Search active or GetAll
GET {{baseUrl}}/menus?categoryId=1&showDeleted=false

### Update
PUT {{baseUrl}}/menus/1
Content-Type: application/json

{
    "name": "Cappuccino",
    "categoryIds": [1],
    "description": "Espresso with steamed milk and foam",
    "imageUrls": ["/assets/images/menus/hot-drinks/cappuccino.jpg"],
    "basePrice": 22000,
    "isAvailable": true,
    "ModifierTypeIds": [1]
}

### Restore Deleted
PATCH {{baseUrl}}/menus/1/restore

### Delete
DELETE {{baseUrl}}/menus/1


###### UPLOADS ######
### Get Upload Auth
GET {{baseUrl}}/images/auth
