###### PAYMENT METHODS ######
### Create
POST {{baseUrl}}/payment-methods
Content-Type: application/json

{
    "code": "QRIS",
    "name": "QRIS",
    "isActive": true
}

### Get by ID
GET {{baseUrl}}/payment-methods/1
Authorization: Bearer {{token}}

### Search active or GetAll
GET {{baseUrl}}/payment-methods
Authorization: Bearer {{token}}

### Update (full replace)
PUT {{baseUrl}}/payment-methods/1
Content-Type: application/json

{
    "code": "QRIS",
    "name": "QRIS",
    "isActive": true
}

### Patch (partial)
PATCH {{baseUrl}}/payment-methods/1
Content-Type: application/json

{
    "isActive": false
}

### Delete (soft delete)
DELETE {{baseUrl}}/payment-methods/1


###### PAYMENTS ######
### Create (targetType: ORDER | DINING)
POST {{baseUrl}}/payments
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "targetType": "ORDER",
    "targetId": 2,
    "paymentMethodId": 1,
    "paymentChannel": null,
    "paymentDetail": "0000123456789",
    "externalId": null,
    "invoiceUrl": null
}

### Mark as paid
POST {{baseUrl}}/payments/1/pay
Authorization: Bearer {{token}}

### Mark as expired
POST {{baseUrl}}/payments/1/expire
Authorization: Bearer {{token}}

### Mark as failed
POST {{baseUrl}}/payments/1/fail
Authorization: Bearer {{token}}

### Mark as refunded
POST {{baseUrl}}/payments/1/refund
Authorization: Bearer {{token}}

### Get by ID
GET {{baseUrl}}/payments/1
Authorization: Bearer {{token}}

### Search active or GetAll
GET {{baseUrl}}/payments?status=PENDING
Authorization: Bearer {{token}}

### Update (full replace)
PUT {{baseUrl}}/payments/1
Content-Type: application/json

{
    "targetType": "ORDER",
    "targetId": 101,
    "paymentMethodId": 2,
    "paymentChannel": "QRIS",
    "paymentDetail": "0000123456789",
    "externalId": null,
    "invoiceUrl": null
}

### Patch (partial)
PATCH {{baseUrl}}/payments/1
Content-Type: application/json

{
    "paymentDetail": "0000987654321"
}

### Delete (soft delete)
DELETE {{baseUrl}}/payments/1
