###### PAYMENTS ######
### Create (targetType: ORDER | DINING) - XENDIT
POST {{baseUrl}}/payments
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "targetType": "ORDER",
    "targetId": 1,
    "paymentProvider": "XENDIT",
    "paymentDetail": "Testing xendit"
}

### Create (targetType: ORDER) - Manual/Cash
POST {{baseUrl}}/payments
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "targetType": "ORDER",
    "targetId": 1,
    "paymentProvider": "INTERNAL",
    "paymentDetail": "Testing internal payment(cash)"
}

### Mark as expired
POST {{baseUrl}}/payments/1/expire
Authorization: Bearer {{token}}

### Mark as failed
POST {{baseUrl}}/payments/1/fail
Authorization: Bearer {{token}}

### Mark as refunded
POST {{baseUrl}}/payments/1/refund
Authorization: Bearer {{token}}

### Get by ID
GET {{baseUrl}}/payments/1
Authorization: Bearer {{token}}

### Search active or GetAll
GET {{baseUrl}}/payments?status=PENDING
Authorization: Bearer {{token}}


### DEPRECATED(NON AVAILABLE)
### Mark as paid
POST {{baseUrl}}/payments/1/pay
Authorization: Bearer {{token}}

### Update (full replace)
PUT {{baseUrl}}/payments/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "targetType": "ORDER",
    "targetId": 101,
    "paymentMethodId": 2,
    "paymentChannel": "QRIS",
    "paymentDetail": "0000123456789",
    "externalId": null,
    "invoiceUrl": null
}

### Patch (partial)
PATCH {{baseUrl}}/payments/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "paymentDetail": "0000987654321"
}

### Delete (soft delete)
DELETE {{baseUrl}}/payments/1
Authorization: Bearer {{token}}
