<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>id.my.rascal</groupId>
        <artifactId>root-backend</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>core-app</artifactId>
    <packaging>jar</packaging>
    <name>core-app</name>
    <description>Main application module</description>

    <dependencies>
        <dependency>
            <groupId>id.my.rascal</groupId>
            <artifactId>auth-core</artifactId>
        </dependency>

        <dependency>
            <groupId>id.my.rascal</groupId>
            <artifactId>menu-core</artifactId>
        </dependency>

        <dependency>
            <groupId>id.my.rascal</groupId>
            <artifactId>order-core</artifactId>
        </dependency>
        <dependency>
            <groupId>id.my.rascal</groupId>
            <artifactId>order-api</artifactId>
        </dependency>

        <dependency>
            <groupId>id.my.rascal</groupId>
            <artifactId>payment-core</artifactId>
        </dependency>
        <dependency>
            <groupId>id.my.rascal</groupId>
            <artifactId>payment-api</artifactId>
        </dependency>
        <dependency>
            <groupId>id.my.rascal</groupId>
            <artifactId>payment-xendit</artifactId>
        </dependency>

        <dependency>
            <groupId>id.my.rascal</groupId>
            <artifactId>dining-core</artifactId>
        </dependency>

        <dependency>
            <groupId>id.my.rascal</groupId>
            <artifactId>image-core</artifactId>
        </dependency>

        <dependency>
            <groupId>id.my.rascal</groupId>
            <artifactId>image-imagekit</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!-- Database Drivers -->
        <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>id.my.rascal.CoreAppApplication</mainClass>
                    <classifier>exec</classifier>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
