spring:
  datasource:
    url: jdbc:postgresql://${database.postgresql.host:localhost}:${database.postgresql.port:5555}/${database.names.core_backend:projekan}?sslmode=${database.postgresql.sslmode:disable}
    username: ${database.username:rascal}
    password: ${database.password:}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      schema-locations: classpath:ddl/postgres/schema-extra.sql
