spring:
  application:
    name: core-backend
  profiles:
    active: postgres
    # active: postgres, dev-seed
    default: postgres, dev-formal
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

server:
  port: 8081
