user rascal users;

events {}

http {
    include "/home/rascal/Documents/!Project!/reverse-proxy/nginx/mime.types";
    default_type application/octet-stream;
    client_max_body_size 10m;
    limit_req_status 429;
    limit_req_zone $binary_remote_addr zone=api_per_ip:10m rate=10r/s;
    # limit_req_zone $binary_remote_addr zone=api_per_ip:10m rate=2r/s;

    server {
        listen 9000;
        access_log "/home/rascal/Documents/!Project!/.assets/run/logs/proxy-access.log";

        location /api/ {
            limit_req zone=api_per_ip burst=20 nodelay;
            # limit_req zone=api_per_ip burst=3 nodelay;

            proxy_pass http://127.0.0.1:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
            root "/home/rascal/Documents/!Project!/frontend/build";
            index index.html;
            try_files $uri $uri.html $uri/ /index.html;
        }
    }
}

