database:
  provider: postgres
  username: postgres
  password: ""
  names:
    core_backend: projekan
  postgresql:
    host: localhost
    port: 5555
    sslmode: disable
  mariadb:
    host: localhost
    port: 3306

seed:
  active: none

services:
  core:
    host: localhost
    port: 8081
  frontend:
    origin: http://localhost:5173

app:
  dev-base-url: https://dev.rascal.my.id

external:
  image_service:
    imagekit:
      url-endpoint:
      public-key:
  xendit:
    base-url: https://api.xendit.co
    public-key: xnd_public_development_qadxOpWzsEL0O4FtQjLz4AShD5aOY3gZCdjO4GC58XV2y9J3NRwN3krpil9f75Ew
