### Login
POST http://localhost:8081/api/auth/login?username=asep&password=qwe


########## AUTHORITIES ##########
### Get by ID
GET http://localhost:8081/api/v1/auths/authorities/1

### Search active or GetAll
GET http://localhost:8081/api/v1/auths/authorities?name=create


########## ROLES ##########
### Create
POST http://localhost:8081/api/v1/auths/roles
Content-Type: application/json

{
    "name": "ADMIN",
    "authorityIds": [1]
}

### Get By ID
GET http://localhost:8081/api/v1/auths/roles/1

### Search active or GetAll
GET http://localhost:8081/api/v1/auths/roles?name=admin



########## USERS ##########
### Create
POST http://localhost:8081/api/v1/auths/users
Content-Type: application/json

{
    "email": "admin@examlple.com",
    "password": "atmin123",
    "roleIds": [1]
}

### Get by ID
GET http://localhost:8081/api/v1/authorities/1

### Search active or GetAll
GET http://localhost:8081/api/v1/authorities?name=create

### Delete
DELETE http://localhost:8081/api/v1/auths/users/1
