### Login
POST http://localhost:8081/api/auth/login?username=asep&password=qwe


########## ROLES ##########
### Create
POST http://localhost:8081/api/v1/roles
Content-Type: application/json

{
    "name": "ADMIN",
    "authorityIds": [1]
}

### Get By ID
GET http://localhost:8081/api/v1/roles/1

### Search active or GetAll
GET http://localhost:8081/api/v1/roles?name=admin



########## AUTHORITIES ##########
### Create
POST http://localhost:8081/api/v1/authorities
Content-Type: application/json

{
    "name": "role.create"
}

### Get by ID
GET http://localhost:8081/api/v1/authorities/1

### Search active or GetAll
GET http://localhost:8081/api/v1/authorities?name=create
