###### MODIFIERS ######
### Create
POST {{baseUrl}}/modifiers
Content-Type: application/json

{
    "name": "Temperature",
    "minSelection": 1,
    "maxSelection": 1,
    "options": [
        { "name": "hot", "additionalPrice": 0 },
        { "name": "ice", "additionalPrice": 500 }
    ]
}

### Get
GET {{baseUrl}}/modifiers/1

### Search active or GetAll
GET {{baseUrl}}/modifiers

### Update
PUT {{baseUrl}}/modifiers/2
Content-Type: application/json

{
    "name": "size",
    "minSelection": 1,
    "maxSelection": 1,
    "options": [
        { "name": "small", "additionalPrice": 0 },
        { "name": "medium", "additionalPrice": 500 },
        { "name": "large", "additionalPrice": 1000 }
    ]
}

### Delete
DELETE {{baseUrl}}/modifiers/2


###### MENU CATEGORIES ######
### Create
POST {{baseUrl}}/menu-categories
Content-Type: application/json

{
    "displayName": "tea",
    "categoryCode": "coffee",
    "displayOrder": 1
}

### Get
GET {{baseUrl}}/menu-categories/1

### Search active or GetAll
GET {{baseUrl}}/menu-categories?displayName=cof&showDeleted=false

### Update
PUT {{baseUrl}}/menu-categories/1
Content-Type: application/json

{
    "displayName": "Hot Beverages",
    "categoryCode": "COffee",
    "displayOrder": 1
}

### Delete
DELETE {{baseUrl}}/menu-categories/2

### Restore
PATCH {{baseUrl}}/menu-categories/1/restore


###### MENUS ######
### Create
POST {{baseUrl}}/menus
Content-Type: application/json

{
    "name": "Cappuccino",
    "categoryIds": [1],
    "description": "Espresso with steamed milk",
    "imageUrls": ["/assets/images/menus/hot-drinks/cappuccino.jpg"],
    "basePrice": 20000,
    "isAvailable": true,
    "ModifierTypeIds": [1]
}

### Get
GET {{baseUrl}}/menus/1

### Search active or GetAll
GET {{baseUrl}}/menus?name=cap&categoryId=1&showDeleted=false

### Update
PUT {{baseUrl}}/menus/1
Content-Type: application/json

{
    "name": "Cappuccino",
    "categoryIds": [1],
    "description": "Espresso with steamed milk and foam",
    "imageUrls": ["/assets/images/menus/hot-drinks/cappuccino.jpg"],
    "basePrice": 22000,
    "isAvailable": true,
    "ModifierTypeIds": [1]
}

### Delete
DELETE {{baseUrl}}/menus/1


###### UPLOADS ######
### Get Upload Auth
GET {{baseUrl}}/images/auth
